"""empty message

Revision ID: 3ac32137f87c
Revises: 0a112fb0a6f9
Create Date: 2025-04-05 21:40:38.111267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac32137f87c'
down_revision = '0a112fb0a6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_fav_user_id_fk_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['fav_user_id_fk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_fav_user_id_fk_fkey', 'profile', ['fav_user_id_fk'], ['id'])

    # ### end Alembic commands ###
